name: Deploy Website

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows to run this workflow manually from the Actions tab.

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout the repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Build the SLSA website from `docs/` directory
        uses: actions/jekyll-build-pages@0143c158f4fa0c5dcd99499a5d00859d79f70b0e # v1.0.7
        with:
            source: ./docs
      - name: Upload build artifacts for deploying
        uses: actions/upload-pages-artifact@66b63f4a7de003f4f00cc8e9af4b83b8f2abdb96 # v1.0.9
  
  deploy:
    permissions:
      pages: write
      id-token: write # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Website
        id: deployment
        uses: actions/deploy-pages@ee48c7b82e077d7b8ef30b50a719e6a792a50c9a # v2.0.2
